### ISSUE TITLE
Adding credentials, the extension is crashed

### ISSUE THREAD

**Issue by tkm-kj** [krtek4/MultiPass#23]
Thank you for update!

But, when I updated the extension and added credentials, the extension was crashed :astonished:

**Comment by krtek4** [comment]
Yeah, it seems there's an issue when adding credentials in the new version.

here is the error :
 ```
Unchecked runtime.lastError while running storage.set: QUOTA_BYTES_PER_ITEM quota exceeded
    at Object.set (chrome-extension://enhldmjbphoeibbpdhmjkchohnidgnah/js/storage.js:29:14)
    at Object.addCredential (chrome-extension://enhldmjbphoeibbpdhmjkchohnidgnah/js/credential_storage.js:30:17)
    at HTMLFormElement.submit (chrome-extension://enhldmjbphoeibbpdhmjkchohnidgnah/js/credentials.js:76:31)
    at HTMLFormElement.n.event.dispatch (chrome-extension://enhldmjbphoeibbpdhmjkchohnidgnah/js/jquery.min.js:3:6404)
    at HTMLFormElement.r.handle (chrome-extension://enhldmjbphoeibbpdhmjkchohnidgnah/js/jquery.min.js:3:3179)
 ```

I'll try to have a look quickly, thanks for reporting this !

**Comment by krtek4** [comment]
I just added version 0.4.3 to the Chrome Store.

This version should fix the issue. Can you please test ?

**Comment by tkm-kj** [comment]
I tested and confirmed that the issue fixed.
Thanks :+1:
